### ISSUE TITLE
Fatal error: Class 'Zend\Http\Client' not found

### ISSUE THREAD

**Issue by colinodell** [zendframework/zend-feed#1]
`zendframework/zend-http` is listed as a suggested package in `composer.json`, but this package doesn't seem to work without it.

**Comment by weierophinney** [comment]
It's marked as suggested (optional) for the following reasons:
- if you're only using the feed writer, it's not needed at all.
- the reader provides an http client interface; you can implement this using whatever code you want, and wire it in to the reader. By default, we provide an implementation that works with zend-http, and this is the default that we attempt to use if no client is otherwise provided.

The point is: it is optional, and the component can be used without it.

**Comment by colinodell** [comment]
Ah okay, that makes sense.

Would you consider mentioning this somewhere in the documentation, perhaps on the [Introduction to Zend\Feed](http://framework.zend.com/manual/current/en/modules/zend.feed.introduction.html) page or a new page about HTTP clients?  The current examples imply that `Reader` "just works" without needing an HTTP client, which led to my confusion and posting this issue.  Besides, I think those are some excellent reasons which other developers might like to know about up front.
